version: '3.8'
services:
  mysql-user:
    image: mysql:8
    container_name: mysql-user
    environment:
      MYSQL_DATABASE: userdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

  mysql-product:
    image: mysql:8
    container_name: mysql-product
    environment:
      MYSQL_DATABASE: productdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql-user

  product-service:
    build: ./product-service
    ports:
      - "8082:8082"
    depends_on:
      - mysql-product