spring.application.name=authservice
server.port=8095

spring.datasource.url=jdbc:mysql://localhost:3306/authdb
spring.datasource.username=root
spring.datasource.password=pass1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8095

# Basic in?memory user for Spring Security login
spring.security.user.name=admin
spring.security.user.password=password

# Auth log

logging.level.org.springframework.security.oauth2.server.authorization=DEBUG
logging.level.org.springframework.security.web.FilterChainProxy=TRACE
logging.level.org.springframework.security.oauth2.provider.endpoint=TRACE

# You?ll see what Spring Security and OAuth2 are doing
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=TRACE
logging.level.org.springframework.web=INFO

# Example for JSON log structure
logging.pattern.console={"time":"%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ}", "level":"%p", "logger":"%c{1}", "message":"%m"}%n



