spring.main.web-application-type=reactive
spring.application.name=api-gateway
server.port=8094

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# JWT validation (Keycloak)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/retail

# Enable discovery routing
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Default filter ? forward JWT
spring.cloud.gateway.default-filters=TokenRelay