app.name=My Interview Service
server.port=8090

#Ex of map config
app.settings.theme=dark
app.settings.language=en
app.settings.timezone=UTC

#spring.profiles.active=preprod

app.mode=dev

#Enable beans endpoint http://localhost:8080/actuator/beans
management.endpoints.web.exposure.include=beans

#select profile
spring.profiles.active=core,core-one,core-two

spring.jpa.open-in-view=false

#AI
spring.ai.openai.api-key=sk-qtNVLaR-3VkRp86CLHIszA
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.temperature=0.7
