server.port=8097

spring.security.oauth2.client.registration.demo-client.client-id=demo-client
spring.security.oauth2.client.registration.demo-client.client-secret=secret
spring.security.oauth2.client.registration.demo-client.scope=read,write
spring.security.oauth2.client.registration.demo-client.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.demo-client.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.demo-client.authorization-uri=http://127.0.0.1:8095/oauth2/authorize
spring.security.oauth2.client.provider.demo-client.token-uri=http://127.0.0.1:8095/oauth2/token
spring.security.oauth2.client.provider.demo-client.user-info-uri=http://127.0.0.1:8095/userinfo
spring.security.oauth2.client.provider.demo-client.user-name-attribute=sub