server:
  port: 8761

spring:
  main:
    web-application-type: servlet
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: false   # usually gateway doesn't register itself
    fetch-registry: false          # gets list of services from Eureka