server:
  port: 8080
  application:
    name: USER-SERVICE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
management:
  endpoints:
    web:
      exposure:
        include: health,info
spring:
  main:
    web-application-type: reactive
  kafka:
    bootstrap-servers: localhost:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        userRegistrationOutput:
          destination: user-registration   # Kafka topic name
          content-type: application/json