server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # Option A: automatic route generation from Eureka registry
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true  # recommended for lowercase naming
      # Option B: manual route definitions using service names
      routes:
        - id: user-service
          uri: lb://USER-SERVICE   # Service name from Eureka
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    register-with-eureka: true    # register Gateway in Eureka
    fetch-registry: true          # enable discovery of other services


management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'