server:
  port: 8080   # Gateway port

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081   # Direct URL
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1
        - id: product-service
          uri: http://localhost:8082   # Direct URL
          predicates:
            - Path=/products/**
          filters:
            - StripPrefix=1

# Actuator config for debugging Gateway
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'