spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   # enables automatic routes from Eureka
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          #uri: http://localhost:8081   # direct URL to User Service
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1             # remove "/users" before forwarding
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          #uri: http://localhost:8082   # direct URL to Product Service
          predicates:
            - Path=/products/**
          filters:
            - StripPrefix=1             # remove "/users" before forwarding
server:
  port: 8080

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,gateway

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      base-path: /actuator    # default
      exposure:
        include: '*'          # exposes all endpoints

debug: true

logging:
  level:
    org.springframework: DEBUG
    com.netflix: DEBUG
    org.springframework.cloud.netflix: DEBUG