server.port=8099

algolia.application-id=ZZLM5LNV17
#This is the ADMIN API key. Please keep it secret and use it ONLY from your backend: this key is used to create, update and DELETE your indices. You can also use it to manage your API keys.
algolia.api-key=e643b09b5b8755aea939ef5e14d1a258
#This is a private API key. Please keep it secret and use it ONLY from your backend: this key is used to create, update and DELETE your indices. You CANNOT use this key to manage your API keys.
algolia.write-key=1651ab3d56d50910c0437c85ff053bf7
#This is the public API key which can be safely used in your frontend code. This key is usable for search queries and it's also able to list the indices you've got access to.
algolia.search-key=dd81cc70680264ca36759b7bf327103b
algolia.index-name=products

# Replicas for sorting
algolia.index-price-asc=products_price_asc
algolia.index-price-desc=products_price_desc
algolia.index-rating-desc=products_rating_desc

# MySQL connection
spring.datasource.url=jdbc:mysql://localhost:3306/shopdb
spring.datasource.username=root
spring.datasource.password=pass1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#If your app is not a web app, disable web environment:
#spring.main.web-application-type=none